convidados = ['Maria', 'Jõao Roberto', 'Victor', 'Carol']
print(f'Você foi convidado(a), {convidados[0]}')
print(f'Você foi convidado(a), {convidados[1]}')
print(f'Você foi convidado(a), {convidados[2]}')
print(f'Você foi convidado(a), {convidados[3]}')
convidados.insert(0, 'Leandro')
print(f'Você foi convidado(a), {convidados[0]}')
convidados.insert(3, 'Lucas')
print(f'Você foi convidado(a), {convidados[3]}')
convidados.append('Júlia')
print(f'Você foi convidado(a), {convidados[-1]}')
print('URGENTE! A mesa não chegará a tempo, apenas duas pessoas poderão ser convidadas.')
convidados.pop()
print(f'Lamentamos, {convidados[-1]}, seu nome foi removido da lista.')
convidados.pop()
print(f'Lamentamos, {convidados[-1]}, seu nome foi removido da lista.')
convidados.pop()
print(f'Lamentamos, {convidados[-1]}, seu nome foi removido da lista.')
convidados.pop()
print(f'Lamentamos, {convidados[-1]}, seu nome foi removido da lista.')
convidados.pop()
print(f'Lamentamos, {convidados[-1]}, seu nome foi removido da lista.')
print(f'Você continua convidado(a), {convidados[0]}')
print(f'Você continua convidado(a), {convidados[-1]}')
del convidados[0]
del convidados[0]
print(convidados)
